services:
  - type: web
    name: offcut-reuse-recommendation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn wsgi:app 
      --workers=1 
      --threads=1 
      --timeout=120 
      --max-requests=100 
      --max-requests-jitter=20
      --worker-class=sync
      --worker-tmp-dir=/dev/shm
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://offcut-recommender.netlify.app
    resources:
      memory: 512MB
      cpu: 0.5
