services:
  - type: web
    name: offcut-reuse-recommendation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn wsgi:app 
      --workers=1 
      --threads=2
      --timeout=60
      --max-requests=50
      --max-requests-jitter=10
      --worker-class=gthread
      --worker-tmp-dir=/dev/shm
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MPLBACKEND
        value: "Agg"
    resources:
      memory: 512MB
      cpu: 0.5
