services:
  - type: web
    name: offcut-reuse-recommendation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://offcut-recommender.netlify.app
    resources:
      memory: 512MB
      cpu: 0.5
